import { IPhotos } from './iphotos.interface';

// The picture-objects for the slider
export let PHOTOS: IPhotos[] = [
  // The wedding-theme
  {
    id: 1,
    title: 'Wedding Photography',
    alts: 'wedding-picture',
    image1: 'Weddings/wedding1.jpg',
    image2: 'Weddings/wedding2.jpg',
    image3: 'Weddings/wedding3.jpg',
    image4: 'Weddings/wedding4.jpg',
    image5: 'Weddings/wedding5.jpg',
    image6: 'Weddings/wedding6.jpg',
    image7: 'Weddings/wedding7.jpg',
    image8: 'Weddings/wedding8.jpg',
    image9: 'Weddings/wedding9.jpg',
    image10: 'Weddings/wedding10.jpg',
  },
  // The newborn-theme
  {
    id: 2,
    title: 'Newborn Pictures',
    alts: 'newborn-picture',
    image1: 'Newborn/baby1.jpg',
    image2: 'Newborn/baby2.jpg',
    image3: 'Newborn/baby3.jpg',
    image4: 'Newborn/baby4.jpg',
    image5: 'Newborn/baby5.jpg',
    image6: 'Newborn/baby6.jpg',
    image7: 'Newborn/baby7.jpg',
    image8: 'Newborn/baby8.jpg',
    image9: 'Newborn/baby9.jpg',
    image10: 'Newborn/baby10.jpg',
  },
  // The event-theme
  {
    id: 3,
    title: 'Event Photography',
    alts: 'event-picture',
    image1: 'Events/party1.jpg',
    image2: 'Events/party2.jpg',
    image3: 'Events/party3.jpg',
    image4: 'Events/party4.jpg',
    image5: 'Events/party5.jpg',
    image6: 'Events/party6.jpg',
    image7: 'Events/party7.jpg',
    image8: 'Events/party8.jpg',
    image9: 'Events/party9.jpg',
    image10: 'Events/party10.jpg',
  },
  // The portrait-theme
  {
    id: 4,
    title: 'Professional Portraits',
    alts: 'personal-portrait',
    image1: 'Portraits/portrait1.jpg',
    image2: 'Portraits/portrait2.jpg',
    image3: 'Portraits/portrait3.jpg',
    image4: 'Portraits/portrait4.jpg',
    image5: 'Portraits/portrait5.jpg',
    image6: 'Portraits/portrait6.jpg',
    image7: 'Portraits/portrait7.jpg',
    image8: 'Portraits/portrait8.jpg',
    image9: 'Portraits/portrait9.jpg',
    image10: 'Portraits/portrait10.jpg',
  },
  // The casting-theme
  {
    id: 5,
    title: 'Casting-Cards',
    alts: 'model-picture',
    image1: 'Casting/model1.jpg',
    image2: 'Casting/model2.jpg',
    image3: 'Casting/model3.jpg',
    image4: 'Casting/model4.jpg',
    image5: 'Casting/model5.jpg',
    image6: 'Casting/model6.jpg',
    image7: 'Casting/model7.jpg',
    image8: 'Casting/model8.jpg',
    image9: 'Casting/model9.jpg',
    image10: 'Casting/model10.jpg',
  },
  // The black&white-theme
  {
    id: 6,
    title: 'Black and White Photos',
    alts: 'monochrome-picture',
    image1: 'BlackWhite/blackWhite1.jpg',
    image2: 'BlackWhite/blackWhite2.jpg',
    image3: 'BlackWhite/blackWhite3.jpg',
    image4: 'BlackWhite/blackWhite4.jpg',
    image5: 'BlackWhite/blackWhite5.jpg',
    image6: 'BlackWhite/blackWhite6.jpg',
    image7: 'BlackWhite/blackWhite7.jpg',
    image8: 'BlackWhite/blackWhite8.jpg',
    image9: 'BlackWhite/blackWhite9.jpg',
    image10: 'BlackWhite/blackWhite10.jpg',
  },
  // The maternity-theme
  {
    id: 7,
    title: 'Maternity Pictures',
    alts: 'maternity-picture',
    image1: 'Maternity/mother1.jpg',
    image2: 'Maternity/mother2.jpg',
    image3: 'Maternity/mother3.jpg',
    image4: 'Maternity/mother4.jpg',
    image5: 'Maternity/mother5.jpg',
    image6: 'Maternity/mother6.jpg',
    image7: 'Maternity/mother7.jpg',
    image8: 'Maternity/mother8.jpg',
    image9: 'Maternity/mother9.jpg',
    image10: 'Maternity/mother10.jpg',
  },
  // The family-theme
  {
    id: 8,
    title: 'Family Pictures',
    alts: 'family-picture',
    image1: 'Families/family1.jpg',
    image2: 'Families/family2.jpg',
    image3: 'Families/family3.jpg',
    image4: 'Families/family4.jpg',
    image5: 'Families/family5.jpg',
    image6: 'Families/family6.jpg',
    image7: 'Families/family7.jpg',
    image8: 'Families/family8.jpg',
    image9: 'Families/family9.jpg',
    image10: 'Families/family10.jpg',
  },
  // The product-theme
  {
    id: 9,
    title: 'Product Displays',
    alts: 'product-picture',
    image1: 'Products/products1.jpg',
    image2: 'Products/products2.jpg',
    image3: 'Products/products3.jpg',
    image4: 'Products/products4.jpg',
    image5: 'Products/products5.jpg',
    image6: 'Products/products6.jpg',
    image7: 'Products/products7.jpg',
    image8: 'Products/products8.jpg',
    image9: 'Products/products9.jpg',
    image10: 'Products/products10.jpg',
  },
];
